apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-users
  labels:
    app: udagram-api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-users
  template:
    metadata:
      labels:
        app: udagram-api-users
    spec:
      containers:
      - name: udagram-api-users
        image: newair007/udagram-api-users
        ports:
        - containerPort: 8081
        env:
          - name: POSTGRES_USERNAME
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: ""
          - name: POSTGRES_DB
            value: "postgres"
          - name: POSTGRES_HOST
            value: "udacity-monolith.cffyih2b8zti.us-east-1.rds.amazonaws.com"
          - name: aws_region
            value: "postgres"
          - name: AWS_PROFILE
            value: ""
          - name: AWS_BUCKET
            value: "postgres"
          - name: JWT_SECRET
            value: ""
          - name: PORT
            value: "8081"